# Generated by Django 5.2.11 on 2026-02-15 10:20

from django.db import migrations

def popular_racas(apps, schema_editor):
    Raca = apps.get_model('vacinacao', 'Raca')
    racas_para_criar = [
        # cachorros
        {'nome': 'Poodle', 'especie': 'cachorro'},
        {'nome': 'Golden Retriver', 'especie': 'cachorro'},
        {'nome': 'Bulldog Francês', 'especie': 'cachorro'},
        {'nome': 'Vira-Lata', 'especie': 'cachorro'},
        {'nome': 'Pinscher', 'especie': 'cachorro'},
        # gatos
        {'nome': 'Persa', 'especie': 'gato'},
        {'nome': 'Siames', 'especie': 'gato'},
        {'nome': 'Maine Coon', 'especie': 'gato'},
        {'nome': 'Vira-lata', 'especie': 'gato'},
        # outros
        {'nome': 'Calopsita', 'especie': 'Outro'},
        {'nome': 'Hamster', 'especie': 'Outro'},
    ]

    for raca in racas_para_criar:
        Raca.objects.get_or_create(nome=raca['nome'], especie=raca['especie'])

def remover_racas(apps, schema_editor):
    Raca = apps.get_model('vacinacao', 'Raca')
    Raca.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_racas, reverse_code=remover_racas),
    ]