# Generated by Django 5.2.11 on 2026-02-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacao', '0002_auto_20260215_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacina',
            options={'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
    ]
