# Generated by Django 5.2.11 on 2026-02-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=150, verbose_name='Sobrenome')),
                ('crmv', models.CharField(max_length=20, unique=True, verbose_name='CRMV')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinário',
                'verbose_name_plural': 'Veterinários',
            },
        ),
    ]
